# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4b459588cf45a64a44d6a298c87aa351"
name = "Dista Sync App"
application_url = "https://process-what-neil-tobago.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,read_price_rules,write_price_rules,read_discounts,write_discounts,write_draft_orders,read_draft_orders,read_fulfillments,write_fulfillments,write_inventory,read_inventory,write_locations,read_locations,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders,read_orders,write_orders,read_products,write_products,read_shipping,write_shipping"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://process-what-neil-tobago.trycloudflare.com/api/auth"
]
